### PR TITLE
Separate text to speed up display. Align text.

### PR DESCRIPTION
**Pull request by jposada202020**
A little PR, just for consideration, trying to keep the non updated text fix, and update the temperature and humidity. Also I aligned the temp and humidity values to the left, not sure if this is the effect wanted or was the result of the scale.  
Feel free disregard this PR if this is not meet your intentions.

Thanks :)

### CODE REVIEW

**Comment by casainho** [comment]
Thank you!

And I will investigate if I can use the uplot you developed!! but I have the 2 variables to show on this small 200x200 pixels and eink display...

**Comment by jposada202020** [comment]
Thank you, I was thinking to use maybe using powerbar from the Adafruit_progressbarlibary, But I was not sure if you wold be interested. Maybe use circuitpython_scales (https://github.com/jposada202020/CircuitPython_scales), was developed thinking about thinks like temperature and humidity.  Let me know happy to help :).

**Comment by casainho** [comment]
I got the uplot working. Is there a way to force a Y scale? for now I see the Y scale adjust to may Y value, and that is not what I am looking for.

I also need to figure out if is possible to write labels, and even the scale values.

And as my display is only BW, I wish to have a filled uplot and other line uplot. But the line will intercept the filled graph, so I wounder if there will be a gap between the line and the filled graph, so the line can be seen.

Also, is there a way to choose the graph background color?

**Comment by jposada202020** [comment]
after further examination you have probably have 0.6.0 version please see https://github.com/jposada202020/CircuitPython_uplot/releases/tag/0.7.0. I was working in some of the changes but have not release the library :)

**Comment by casainho** [comment]
I will check it later and see if it works for my needs. Will report.

**Pull request merged**
